package demo

import org.openbaton.catalogue.mano.common.monitoring.Alarm
import org.openbaton.catalogue.mano.common.monitoring.AlarmState;

global org.slf4j.Logger logger;

rule "Init Process"
    when
        a : Alarm()
    then
        logger.info("\t==> Init jbpm process");
        //drools.getKnowledgeRuntime().startProcess( "alarm" );
end

rule "update an alarm"
    when
        a : Alarm( resourceId == "host-example", alarmState == AlarmState.FIRED )
    then
        //System.out.println( myMessage );
        logger.info("\t==> Updating " + a);
        a.setAlarmState(AlarmState.UPDATED);
        update( a );
end

rule "update an alarm"
    when
        a : Alarm( resourceId == "host-example", alarmState == AlarmState.UPDATED )
    then
        //System.out.println( myMessage );
        logger.info("\t==> updated " + a);
        a.setAlarmState(AlarmState.UPDATED);
        update( a );
end

