import org.openbaton.faultmanagement.fc.RecoveryAction
import org.openbaton.faultmanagement.fc.RecoveryActionStatus

global org.slf4j.Logger logger

rule "Recovery action finished"
    when
       recoveryActionEnd : RecoveryAction(status == RecoveryActionStatus.FINISHED)
       recoveryActionActual : RecoveryAction(status == RecoveryActionStatus.IN_PROGRESS)
    then
        logger.info("The following recovery action is finished " + recoveryActionActual);

        delete(recoveryActionActual);
        delete(recoveryActionEnd);
end
