import org.openbaton.catalogue.mano.common.monitoring.*
import org.openbaton.faultmanagement.fc.repositories.VNFAlarmRepository
import org.openbaton.catalogue.mano.record.VNFCInstance
import org.openbaton.faultmanagement.fc.policymanagement.interfaces.PolicyManager
import org.openbaton.catalogue.mano.record.VirtualNetworkFunctionRecord
import org.openbaton.faultmanagement.fc.interfaces.NSRManager
import org.slf4j.Logger
import org.openbaton.faultmanagement.fc.RecoveryAction
import org.openbaton.faultmanagement.ha.HighAvailabilityManager
import org.openbaton.catalogue.mano.descriptor.VirtualDeploymentUnit
import java.text.DateFormat
import java.text.SimpleDateFormat
import java.util.Date

global HighAvailabilityManager highAvailabilityManager
global VNFAlarmRepository vnfAlarmRepository
global PolicyManager policyManager
global Logger logger
global NSRManager nsrManager


/// Whether we whant to correlate alarm from different VNF manager




