import org.openbaton.catalogue.mano.common.monitoring.*
import org.openbaton.faultmanagement.fc.repositories.AlarmRepository
import org.openbaton.catalogue.mano.record.VNFCInstance
import org.openbaton.faultmanagement.fc.policymanagement.interfaces.PolicyManager
import org.openbaton.faultmanagement.fc.policymanagement.interfaces.MonitoringManager
import org.openbaton.faultmanagement.fc.interfaces.NSRManager
import org.openbaton.catalogue.mano.record.VirtualNetworkFunctionRecord

global MonitoringManager monitoringManager
global PolicyManager policyManager
global org.slf4j.Logger logger
global NSRManager nsrManager


rule "Get a managed VR alarm and create a VNF alarm"
    agenda-group "correlation"
    when
        a : VRAlarm( thresholdId : thresholdId, managedObject : managedObject,
        alarmState == AlarmState.FIRED , alarmType == AlarmType.VIRTUALIZED_RESOURCE ,
         perceivedSeverity == PerceivedSeverity.CRITICAL)
        vnfcInstance : VNFCInstance() from nsrManager.getVNFCInstance(managedObject)
        eval( policyManager.isAManagedAlarm(thresholdId) )
    then
        logger.info("\tReceived a managed VR alarm regarding the managedObject" + managedObject);

        logger.info("\tthe vnfcinstance is " + vnfcInstance);

        //Create a VNFAlarm from the VRAlarm received
        VNFAlarm vnfAlarm = new VNFAlarm();
        vnfAlarm.setAlarmState(AlarmState.FIRED);
        vnfAlarm.setPerceivedSeverity(PerceivedSeverity.CRITICAL);
        vnfAlarm.addVnfcId(vnfcInstance.getId());
        vnfAlarm.setVimName(vnfcInstance.getVim_id());

        // Set the vnfrId
        String policyId = policyManager.getPolicyIdByThresholdId(a.getThresholdId());
        String vnfrId = policyManager.getVnfrIdByPolicyId(policyId);
        vnfAlarm.setVnfrId(vnfrId);

        vnfAlarm.addCorrelatedAlarmId(a.getThresholdId());

        insert( vnfAlarm );
end

rule "Get an unmanaged VR alarm and create a VNF alarm"
    agenda-group "correlation"
    when
        a : VRAlarm( thresholdId : thresholdId, managedObject : managedObject,
        alarmState == AlarmState.FIRED , alarmType == AlarmType.VIRTUALIZED_RESOURCE ,
         perceivedSeverity == PerceivedSeverity.CRITICAL)
        vnfcInstance : VNFCInstance() from nsrManager.getVNFCInstance(managedObject)
        eval( !policyManager.isAManagedAlarm(thresholdId) )
    then
        logger.info("\tReceived an unmanaged VR alarm regarding the managedObject: " + managedObject);

        logger.info("\tthe vnfcinstance is " + vnfcInstance);

        //Create a VNFAlarm from the VRAlarm received
        VNFAlarm vnfAlarm = new VNFAlarm();
        vnfAlarm.setAlarmState(AlarmState.FIRED);
        vnfAlarm.setPerceivedSeverity(PerceivedSeverity.CRITICAL);
        vnfAlarm.addVnfcId(vnfcInstance.getId());
        vnfAlarm.setVimName(vnfcInstance.getVim_id());

        // Set the vnfrId
        VirtualNetworkFunctionRecord vnfr = nsrManager.getVirtualNetworkFunctionRecordFromVNFCHostname(vnfcInstance.getHostname());
        vnfAlarm.setVnfrId(vnfr.getId());

        logger.debug("Created VNF alarm "+vnfAlarm);
        //Check..
        //vnfAlarm.addCorrelatedAlarmId(a.getThresholdId());

        insert( vnfAlarm );
end

rule "A VNF alarm is created"
    agenda-group "correlation"
    when
        vnfAlarm : VNFAlarm(  alarmState == AlarmState.FIRED )
    then
        logger.info("\tFired a VNFAlarm! " + vnfAlarm);
end

rule "Example"
    agenda-group "correlation"
    when
        eval(true)
    then
        logger.debug("\t Drools rule fired! ");
end

